# Generated by Django 6.0.5 on 2026-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
