# Generated by Django 6.0.5 on 2026-06-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='completed_at',
        ),
    ]
