# Generated by Django 6.0.5 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_completed_at'),
        ('properties', '0003_rename_address_property_street_property_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('owner', 'Propietario'), ('buyer', 'Comprador')], default='owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='contacts', to='properties.property'),
        ),
    ]
