# Generated by Django 6.0.5 on 2026-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_contact_type_alter_contact_email_and_more'),
        ('properties', '0006_alter_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='contact',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Piso / Puerta'),
        ),
        migrations.AddField(
            model_name='contact',
            name='identification_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='DNI / NIE / Pasaporte'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('partner', 'Pareja de hecho'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='properties.property'),
        ),
    ]
