# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_archiving'),
        ('properties', '0015_alter_property_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_agent', 'is_archived'], name='contact_agent_archived'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['identification_number'], name='contact_identity_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contact_phone_idx'),
        ),
    ]
