# Generated by Django 6.0.5 on 2026-06-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0005_property_area_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], max_length=20)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactado'), ('follow_up', 'Seguimiento'), ('appointment', 'Cita programada'), ('closed', 'Cerrada')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
        ),
    ]
