# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscomment_audit'),
        ('properties', '0015_alter_property_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='news_agent_status_created'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.CheckConstraint(condition=models.Q(('client_price__gt', 0), ('estimated_price__gt', 0)), name='news_positive_prices'),
        ),
    ]
