# Generated by Django 6.0.5 on 2026-08-20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("scope", models.CharField(choices=[("individual", "Individual"), ("team", "Grupal")], default="individual", max_length=20, verbose_name="Tipo de objetivo")),
                ("metric", models.CharField(choices=[("listings", "Encargos"), ("orders", "Pedidos"), ("news", "Noticias"), ("sale_appointments", "Citas de venta"), ("acquisition_appointments", "Citas de adquisición"), ("follow_up_appointments", "Citas de seguimiento"), ("contacts", "Contactos"), ("properties", "Inmuebles"), ("vacant_properties", "Inmuebles vacíos"), ("tenant_properties", "Inmuebles con inquilinos"), ("proposals", "Propuestas"), ("sales", "Ventas firmadas"), ("rentals", "Alquileres firmados")], max_length=40, verbose_name="Elemento que se debe conseguir")),
                ("target_count", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Cantidad objetivo")),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de finalización")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignees", models.ManyToManyField(related_name="goals", to=settings.AUTH_USER_MODEL, verbose_name="Agentes participantes")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_goals", to=settings.AUTH_USER_MODEL, verbose_name="Creado por")),
            ],
            options={
                "verbose_name": "Objetivo",
                "verbose_name_plural": "Objetivos",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
    ]
