# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_contact_activity_task'),
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('tasks', '0008_task_task_agent_status_due_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'created_at'], name='activity_user_created'),
        ),
    ]
