# Generated by Django 6.0.5 on 2026-06-22 00:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0002_initial'),
        ('properties', '0006_alter_property_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Cancelado'), ('sold', 'Vendido'), ('rented', 'Alquilado')], default='active', max_length=20)),
                ('owner_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agency_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property')),
                ('source_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_listing', to='calendar_app.appointment')),
            ],
        ),
    ]
