# Generated by Django 6.0.5 on 2026-06-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_diference',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
