# Generated by Django 6.0.5 on 2026-08-03 19:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contact_status_contact_birth_date_and_more'),
        ('listings', '0002_listing_price_diference'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión acordada (%)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='contacts.contact'),
        ),
    ]
