# Generated by Django 6.0.5 on 2026-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='workflow_status',
            field=models.CharField(choices=[('active', 'Activo'), ('follow_up_appointment', 'Seguimiento programado'), ('sale_appointment', 'Visita programada'), ('proposal_appointment', 'Cita de propuesta programada'), ('proposal', 'Propuesta recibida'), ('closed', 'Cerrado')], default='active', max_length=30, verbose_name='Estado del proceso'),
        ),
    ]
