# Generated by Django 6.0.5 on 2026-08-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='workflow_status',
            field=models.CharField(choices=[('active', 'Activo'), ('follow_up_appointment', 'Seguimiento programado'), ('sale_appointment', 'Visita programada'), ('proposal_appointment', 'Cita de propuesta programada'), ('proposal', 'Propuesta recibida'), ('acceptance_appointment', 'Aceptación programada'), ('counteroffer', 'Contraoferta recibida'), ('contract_appointment', 'Contrato programado'), ('signing_appointment', 'Escrituración programada'), ('closed', 'Cerrado')], default='active', max_length=30, verbose_name='Estado del proceso'),
        ),
    ]
