# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_appointment_appt_agent_status_date_and_more'),
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('listings', '0009_listingcomment_audit'),
        ('properties', '0015_alter_property_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['agent', 'status', 'end_date'], name='listing_agent_status_end'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'workflow_status'], name='listing_status_workflow'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='listing_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('owner_price__gte', 0), ('agency_price__gte', 0), ('agreed_price__gt', 0), models.Q(('commission_amount__isnull', True), ('commission_amount__gte', 0), _connector='OR')), name='listing_valid_amounts'),
        ),
    ]
