# Generated by Django 6.0.5 on 2026-08-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_appointment_result_comment_and_more'),
        ('listings', '0004_listingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_appointments', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='call',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('acquisition', 'Adquisición'), ('sale', 'Venta'), ('valuation', 'Valoración'), ('signing', 'Firma'), ('follow_up', 'Seguimiento')], max_length=20),
        ),
    ]
