# Generated by Django 6.0.5 on 2026-08-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_appointment_listing_call_listing_and_more'),
        ('contacts', '0006_remove_contact_status_contact_birth_date_and_more'),
        ('listings', '0004_listingcomment'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_appointments', to='orders.order'),
        ),
        migrations.CreateModel(
            name='ProposalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del encargo')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio ofertado')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Señal entregada')),
                ('proposal_date', models.DateField(verbose_name='Fecha de creación')),
                ('end_date', models.DateField(verbose_name='Fecha final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_proposals', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_proposals', to='contacts.contact')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='listings.listing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='orders.order')),
                ('source_sale_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='calendar_app.appointment')),
            ],
        ),
    ]
