# Generated by Django 6.0.5 on 2026-08-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_appointment_order_proposalappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalappointment',
            options={'verbose_name': 'Propuesta de compra', 'verbose_name_plural': 'Propuestas de compra'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='source_sale_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_appointment', to='calendar_app.appointment', verbose_name='Cita de venta origen'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('acquisition', 'Adquisición'), ('sale', 'Venta'), ('valuation', 'Valoración'), ('signing', 'Firma'), ('follow_up', 'Seguimiento'), ('proposal', 'Propuesta')], max_length=20),
        ),
    ]
