# Generated by Django 6.0.5 on 2026-08-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_sync_workflow_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='purchase_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='calendar_app.proposalappointment', verbose_name='Propuesta de compra'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source_acceptance_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_appointments', to='calendar_app.appointment', verbose_name='Cita de aceptación origen'),
        ),
        migrations.AddField(
            model_name='proposalappointment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Presentada'), ('acceptance_appointment', 'Cita de aceptación programada'), ('accepted', 'Aceptada'), ('counteroffer', 'Contraoferta recibida'), ('contract_appointment', 'Cita de contrato programada'), ('signing_appointment', 'Cita de escrituración programada')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('acquisition', 'Adquisición'), ('sale', 'Venta'), ('valuation', 'Valoración'), ('signing', 'Escrituración'), ('follow_up', 'Seguimiento'), ('proposal', 'Propuesta'), ('proposal_acceptance', 'Aceptación de propuesta'), ('contract', 'Contrato')], max_length=20),
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counteroffer_date', models.DateField(verbose_name='Fecha de la contraoferta')),
                ('owner_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio solicitado por el propietario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counteroffers', to='calendar_app.proposalappointment')),
                ('source_acceptance_appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='counteroffer', to='calendar_app.appointment')),
            ],
            options={
                'verbose_name': 'Contraoferta',
                'verbose_name_plural': 'Contraofertas',
                'ordering': ['-counteroffer_date', '-created_at'],
            },
        ),
    ]
