# Generated by Django 6.0.5 on 2026-08-06 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_appointment_purchase_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='calendar_app.call')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de llamada',
                'verbose_name_plural': 'Comentarios de llamada',
                'ordering': ['-created_at'],
            },
        ),
    ]
