# Generated by Django 6.0.5 on 2026-08-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_callcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source_counteroffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_appointments', to='calendar_app.counteroffer', verbose_name='Contraoferta a la que responde'),
        ),
    ]
