# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0015_financial_advice_appointment'),
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('listings', '0009_listingcomment_audit'),
        ('news', '0004_news_news_agent_status_created_and_more'),
        ('orders', '0010_order_order_agent_status_updated_and_more'),
        ('properties', '0015_alter_property_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['agent', 'status', 'date'], name='appt_agent_status_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'date'], name='appt_status_date'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['agent', 'status', 'date'], name='call_agent_status_date'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status', 'date'], name='call_status_date'),
        ),
        migrations.AddIndex(
            model_name='proposalappointment',
            index=models.Index(fields=['agent', 'status', 'end_date'], name='proposal_agent_status_end'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('time'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='counteroffer',
            constraint=models.CheckConstraint(condition=models.Q(('owner_price__gt', 0)), name='counteroffer_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='proposalappointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('proposal_date'))), name='proposal_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='proposalappointment',
            constraint=models.CheckConstraint(condition=models.Q(('listing_price__gt', 0), ('offered_price__gt', 0), ('deposit_amount__gte', 0)), name='proposal_valid_amounts'),
        ),
    ]
