# Generated by Django 6.0.5 on 2026-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(choices=[('flat', 'Piso'), ('house', 'Casa'), ('villa', 'Villa'), ('office', 'Oficina')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
