# Generated by Django 6.0.5 on 2026-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('reserved', 'Reservado'), ('sold', 'Vendido')], default='active', max_length=20),
        ),
    ]
