# Generated by Django 6.0.5 on 2026-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_zone_property_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(blank=True, help_text='Superficie en m²', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='built_area',
            field=models.PositiveIntegerField(blank=True, help_text='Superficie construida en m²', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('rented', 'Alquilado'), ('prospect', 'Borrador')], default='prospect', max_length=20),
        ),
    ]
