# Generated by Django 6.0.5 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Piso'), ('house', 'Casa'), ('villa', 'Villa'), ('office', 'Oficina'), ('local', 'Local'), ('solar', 'Solar'), ('terreno', 'Terreno')], max_length=20),
        ),
    ]
