# Generated by Django 6.0.5 on 2026-08-16 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_property_states(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    News = apps.get_model("news", "News")
    Listing = apps.get_model("listings", "Listing")
    Sale = apps.get_model("sales", "Sale")

    Property.objects.filter(status="prospect").update(status="never_contacted")
    Property.objects.filter(status="rented").update(
        status="rented",
        occupied_by="tenants",
    )
    Property.objects.filter(status="reserved").update(status="in_listing")

    for property_obj in Property.objects.all():
        if Sale.objects.filter(
            related_property_id=property_obj.pk,
            status="signed",
        ).exists() or Listing.objects.filter(
            property_id=property_obj.pk,
            status="sold",
        ).exists():
            status = "sold"
        elif Listing.objects.filter(
            property_id=property_obj.pk,
            status="rented",
        ).exists():
            status = "rented"
        elif Listing.objects.filter(
            property_id=property_obj.pk,
            status="active",
        ).exists():
            status = "in_listing"
        elif News.objects.filter(related_property_id=property_obj.pk).exists():
            status = "news"
        elif property_obj.status not in {
            "sold",
            "rented",
            "in_listing",
            "never_contacted",
        }:
            status = "never_contacted"
        else:
            status = property_obj.status

        Property.objects.filter(pk=property_obj.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_price_remove_property_title_and_more'),
        ('news', '0002_news_agent_newscomment_user'),
        ('listings', '0006_alter_listing_workflow_status'),
        ('sales', '0002_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='occupied_by',
            field=models.CharField(choices=[('vacant', 'Vacío'), ('owner', 'Propietario'), ('tenants', 'Inquilinos')], default='owner', max_length=20, verbose_name='Ocupado por'),
        ),
        migrations.RunPython(
            migrate_property_states,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('news', 'Noticia'), ('never_contacted', 'Nunca contactado'), ('contacted', 'Contactado'), ('contacted_30', 'Contactado hace más de 30 días'), ('vacant', 'Vacío'), ('in_listing', 'En encargo'), ('sold', 'Vendido'), ('rented', 'Alquilado')], default='never_contacted', editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de inmueble',
                'verbose_name_plural': 'Comentarios de inmuebles',
                'ordering': ['-created_at'],
            },
        ),
    ]
