# Generated by Django 6.0.5 on 2026-08-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_occupied_by_alter_property_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('news', 'Noticia'), ('never_contacted', 'Nunca contactado'), ('contacted', 'Contactado'), ('contacted_30', 'Contactado hace más de 30 días'), ('vacant', 'Vacío'), ('in_listing', 'En encargo'), ('sold', 'Vendido'), ('rented', 'Alquilado')], max_length=30, verbose_name='Estado anterior')),
                ('new_status', models.CharField(choices=[('news', 'Noticia'), ('never_contacted', 'Nunca contactado'), ('contacted', 'Contactado'), ('contacted_30', 'Contactado hace más de 30 días'), ('vacant', 'Vacío'), ('in_listing', 'En encargo'), ('sold', 'Vendido'), ('rented', 'Alquilado')], max_length=30, verbose_name='Estado nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='properties.property')),
            ],
            options={
                'verbose_name': 'Cambio de estado de inmueble',
                'verbose_name_plural': 'Cambios de estado de inmuebles',
                'ordering': ['-created_at'],
            },
        ),
    ]
