# Generated by Django 6.0.5 on 2026-08-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertystatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Piso'), ('house', 'Casa'), ('villa', 'Villa'), ('office', 'Oficina'), ('local', 'Local'), ('nave', 'Nave'), ('solar', 'Solar'), ('terreno', 'Terreno')], max_length=20),
        ),
    ]
