# Generated by Django 6.0.5 on 2026-09-01 22:07

import config.validators
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertycomment_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_upload_to, validators=[config.validators.validate_property_image]),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['assigned_agent', 'is_archived', 'status'], name='property_agent_archive_status'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='property_status_created'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'street', 'number'], name='property_address_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='property_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='property_valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='property_complete_coordinates'),
        ),
    ]
