# Generated by Django 6.0.5 on 2026-06-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='property',
            new_name='related_property',
        ),
    ]
