# Generated by Django 6.0.5 on 2026-08-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contact_status_contact_birth_date_and_more'),
        ('properties', '0007_remove_property_price_remove_property_title_and_more'),
        ('tasks', '0003_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('custom', 'Personalizada'), ('zone_sweep', 'Barrer una zona')], default='custom', max_length=20, verbose_name='Tipo de tarea'),
        ),
        migrations.AddField(
            model_name='task',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='properties.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
    ]
