# Generated by Django 6.0.5 on 2026-08-10 22:15

from django.db import migrations, models


def rename_zone_tasks(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    prefix = "Barrer zona "
    for task in Task.objects.filter(
        task_type="zone_sweep",
        title__startswith=prefix,
    ).iterator():
        task.title = f"Peinar zona {task.title[len(prefix):]}"
        task.save(update_fields=["title"])


def restore_zone_task_names(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    prefix = "Peinar zona "
    for task in Task.objects.filter(
        task_type="zone_sweep",
        title__startswith=prefix,
    ).iterator():
        task.title = f"Barrer zona {task.title[len(prefix):]}"
        task.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_type_task_zone_alter_task_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('custom', 'Personalizada'), ('zone_sweep', 'Peinar una zona')], default='custom', max_length=20, verbose_name='Tipo de tarea'),
        ),
        migrations.RunPython(rename_zone_tasks, restore_zone_task_names),
    ]
