# Generated by Django 6.0.5 on 2026-08-10 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Días consecutivos'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
