# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('properties', '0015_alter_property_image_and_more'),
        ('tasks', '0007_street_task_streets_and_street_sweep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='task_agent_status_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', 'schedule_date'], name='task_agent_status_sched'),
        ),
    ]
