# Generated by Django 6.0.5 on 2026-08-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_remove_contact_status_contact_birth_date_and_more'),
        ('properties', '0007_remove_property_price_remove_property_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto máximo')),
                ('payment_type', models.CharField(choices=[('cash', 'Contado'), ('financing', 'Financiación')], max_length=20, verbose_name='Tipo de pago')),
                ('property_type', models.CharField(choices=[('flat', 'Piso'), ('house', 'Casa'), ('villa', 'Villa'), ('office', 'Oficina'), ('local', 'Local'), ('solar', 'Solar'), ('terreno', 'Terreno')], max_length=20, verbose_name='Tipo de inmueble')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baños')),
                ('notes', models.TextField(blank=True, verbose_name='Otra información')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'contact_type': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.contact')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='properties.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
