# Generated by Django 6.0.5 on 2026-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('sale_appointment', 'Cita de venta programada'), ('proposal_appointment', 'Cita de propuesta programada'), ('proposal', 'Propuesta realizada'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='active', max_length=30),
        ),
    ]
