# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('orders', '0009_financial_advice_status'),
        ('properties', '0015_alter_property_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agent', 'status', 'updated_at'], name='order_agent_status_updated'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__gt', 0)), name='order_positive_max_price'),
        ),
    ]
