# Generated by Django 6.0.5 on 2026-06-03 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_assigned_agent'),
        ('properties', '0002_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('cancelled', 'Cancelada')], default='signed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='contacts.contact')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='properties.property')),
            ],
        ),
    ]
