# Generated by Django 6.0.5 on 2026-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
    ]
