# Generated by Django 6.0.5 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_appointment_appt_agent_status_date_and_more'),
        ('contacts', '0010_contact_contact_agent_archived_and_more'),
        ('listings', '0010_listing_listing_agent_status_end_and_more'),
        ('orders', '0010_order_order_agent_status_updated_and_more'),
        ('properties', '0015_alter_property_image_and_more'),
        ('sales', '0006_salecorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['agent', 'status', 'contract_date'], name='rental_agent_status_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['agent', 'status', 'sale_date'], name='sale_agent_status_date'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='rental_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(condition=models.Q(('rent_price__gt', 0), ('deposit_amount__gte', 0), ('owner_commission__gte', 0), ('tenant_commission__gte', 0), ('earnest_money_amount__gte', 0)), name='rental_valid_amounts'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gt', 0), ('commission_amount__gte', 0), ('seller_commission__gte', 0), ('buyer_commission__gte', 0), ('deposit_amount__gte', 0), ('earnest_money_amount__gte', 0)), name='sale_valid_amounts'),
        ),
    ]
